agentConfigs:
  kafkaServerProperties: /etc/kafka/server.properties
  serverUrl: http://localhost:8444/admin/api
  clusterId: testkafka
  readOnly: true
  enableServiceMetrics: true
statsConfigs:
  enabled: false